CREATE TABLE "roles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"role_key" text NOT NULL,
	"role_name" text NOT NULL,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "roles_role_key_unique" UNIQUE("role_key")
);
--> statement-breakpoint
CREATE TABLE "permissions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"role_id" uuid NOT NULL,
	"module" text NOT NULL,
	"can_view" boolean DEFAULT false NOT NULL,
	"can_create" boolean DEFAULT false NOT NULL,
	"can_edit" boolean DEFAULT false NOT NULL,
	"can_delete" boolean DEFAULT false NOT NULL,
	"extra_actions" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"port_code" text NOT NULL,
	"name" text NOT NULL,
	"island" text,
	"country" text NOT NULL,
	"status" text DEFAULT 'Active' NOT NULL,
	"default_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ports_port_code_unique" UNIQUE("port_code")
);
--> statement-breakpoint
CREATE TABLE "agents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"agent_code" text NOT NULL,
	"name" text NOT NULL,
	"contact_person" text,
	"email" text,
	"phone" text,
	"territory" text,
	"address" text,
	"assigned_port_code" text,
	"status" text DEFAULT 'Active' NOT NULL,
	"rating" text DEFAULT '5.0/5',
	"credit_limit_usd" numeric(12, 2) DEFAULT '0.00',
	"current_balance_usd" numeric(12, 2) DEFAULT '0.00',
	"last_activity" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "agents_agent_code_unique" UNIQUE("agent_code")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_code" text,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"name" text NOT NULL,
	"role_key" text NOT NULL,
	"department" text,
	"status" text DEFAULT 'Active' NOT NULL,
	"avatar" text,
	"last_login" text,
	"phone" text,
	"agent_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_user_code_unique" UNIQUE("user_code"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "customers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_number" text NOT NULL,
	"name" text NOT NULL,
	"company_name" text NOT NULL,
	"contact_person" text,
	"email" text,
	"telephone" text,
	"phone" text,
	"address" text,
	"destination_port" text,
	"destination_code" text,
	"tax_id" text,
	"account_type" text,
	"credit_terms" text,
	"notes" text,
	"status" text DEFAULT 'Active' NOT NULL,
	"created_date" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "customers_customer_number_unique" UNIQUE("customer_number")
);
--> statement-breakpoint
CREATE TABLE "warehouse_receipts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"receipt_number" text NOT NULL,
	"sequence_number" integer NOT NULL,
	"date" text NOT NULL,
	"time" text,
	"customer_id" uuid,
	"customer_name" text NOT NULL,
	"shipper" text,
	"consignee" text,
	"agent_id" uuid,
	"agent_name" text,
	"destination_port" text NOT NULL,
	"destination_code" text NOT NULL,
	"cargo_description" text,
	"package_count" integer DEFAULT 1 NOT NULL,
	"total_pieces" integer DEFAULT 1 NOT NULL,
	"package_type" text,
	"packages" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"length_inches" numeric(10, 2),
	"width_inches" numeric(10, 2),
	"height_inches" numeric(10, 2),
	"weight_lbs" numeric(10, 2),
	"weight_kg" numeric(10, 2),
	"total_cft" numeric(10, 2),
	"total_cbm" numeric(10, 2),
	"warehouse_location" text DEFAULT 'CFS Miami',
	"status" text DEFAULT 'Ready for Consolidation' NOT NULL,
	"hazardous" boolean DEFAULT false NOT NULL,
	"fragile" boolean DEFAULT false NOT NULL,
	"notes" text,
	"barcode" text,
	"qr_code" text,
	"assigned_house_bill_id" text,
	"assigned_consolidation_id" text,
	"assigned_shipment_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "warehouse_receipts_receipt_number_unique" UNIQUE("receipt_number"),
	CONSTRAINT "warehouse_receipts_sequence_number_unique" UNIQUE("sequence_number")
);
--> statement-breakpoint
CREATE TABLE "cargo" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"cargo_number" text NOT NULL,
	"warehouse_receipt_id" uuid NOT NULL,
	"receipt_number" text NOT NULL,
	"customer" text NOT NULL,
	"description" text NOT NULL,
	"package_count" integer DEFAULT 1 NOT NULL,
	"total_pieces" integer DEFAULT 1 NOT NULL,
	"package_type" text,
	"length_inches" numeric(10, 2),
	"width_inches" numeric(10, 2),
	"height_inches" numeric(10, 2),
	"weight_lbs" numeric(10, 2),
	"weight_kg" numeric(10, 2),
	"cft" numeric(10, 2),
	"cbm" numeric(10, 2),
	"warehouse_location" text DEFAULT 'CFS Miami',
	"destination_port" text,
	"destination_code" text,
	"status" text DEFAULT 'Ready for Consolidation' NOT NULL,
	"barcode" text,
	"qr_code" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cargo_cargo_number_unique" UNIQUE("cargo_number")
);
--> statement-breakpoint
CREATE TABLE "house_bills" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hbl_number" text NOT NULL,
	"customer_id" uuid,
	"customer_name" text NOT NULL,
	"shipper" jsonb NOT NULL,
	"consignee" jsonb NOT NULL,
	"notify_party" jsonb,
	"agent_id" uuid,
	"agent_name" text,
	"origin_port" text DEFAULT 'Port of Miami (USMIA), FL' NOT NULL,
	"destination_port" text NOT NULL,
	"destination_code" text NOT NULL,
	"warehouse_receipt_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"cargo_description" text,
	"packages" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"total_packages" integer DEFAULT 0 NOT NULL,
	"total_pieces" integer DEFAULT 0 NOT NULL,
	"total_weight_lbs" numeric(10, 2) DEFAULT '0.00',
	"total_weight_kg" numeric(10, 2) DEFAULT '0.00',
	"total_cft" numeric(10, 2) DEFAULT '0.00',
	"total_cbm" numeric(10, 2) DEFAULT '0.00',
	"status" text DEFAULT 'Active' NOT NULL,
	"freight_terms" text DEFAULT 'Freight Prepaid' NOT NULL,
	"created_date" text NOT NULL,
	"issue_date" text,
	"assigned_consolidation_id" text,
	"assigned_master_bl_id" text,
	"assigned_shipment_id" text,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "house_bills_hbl_number_unique" UNIQUE("hbl_number")
);
--> statement-breakpoint
CREATE TABLE "containers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"container_number" text NOT NULL,
	"type" text NOT NULL,
	"carrier" text,
	"seal_number" text,
	"tare_weight_kg" numeric(10, 2),
	"max_payload_kg" numeric(10, 2),
	"max_volume_cbm" numeric(10, 2),
	"loaded_weight_kg" numeric(10, 2) DEFAULT '0.00',
	"loaded_volume_cbm" numeric(10, 2) DEFAULT '0.00',
	"fill_percentage" numeric(5, 2) DEFAULT '0.00',
	"current_shipment_id" text,
	"current_shipment_number" text,
	"status" text DEFAULT 'Available at CFS Yard' NOT NULL,
	"location" text,
	"origin_port" text,
	"discharge_port" text,
	"temperature_controlled" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "containers_container_number_unique" UNIQUE("container_number")
);
--> statement-breakpoint
CREATE TABLE "vessels" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"imo_number" text NOT NULL,
	"flag" text,
	"type" text,
	"carrier" text,
	"capacity_teu" integer,
	"deadweight_tonnage" integer,
	"built_year" integer,
	"status" text DEFAULT 'Scheduled' NOT NULL,
	"current_voyage" text,
	"active_route" text,
	"eta_next_port" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "vessels_imo_number_unique" UNIQUE("imo_number")
);
--> statement-breakpoint
CREATE TABLE "voyages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"voyage_number" text NOT NULL,
	"vessel_id" uuid,
	"vessel_name" text NOT NULL,
	"carrier" text,
	"origin_port" text NOT NULL,
	"destination_port" text NOT NULL,
	"departure_date" text,
	"arrival_date" text,
	"status" text DEFAULT 'Scheduled' NOT NULL,
	"assigned_shipments_count" integer DEFAULT 0 NOT NULL,
	"total_teu_utilized" numeric(6, 2) DEFAULT '0.00',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "voyages_voyage_number_unique" UNIQUE("voyage_number")
);
--> statement-breakpoint
CREATE TABLE "consolidations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"consolidation_number" text NOT NULL,
	"title" text NOT NULL,
	"destination_port" text NOT NULL,
	"destination_code" text NOT NULL,
	"created_date" text NOT NULL,
	"status" text DEFAULT 'Planning' NOT NULL,
	"container_id" uuid,
	"container_number" text,
	"container_type" text,
	"container_capacity_cbm" numeric(10, 2),
	"seal_number" text,
	"vessel_id" uuid,
	"vessel_name" text,
	"voyage_id" uuid,
	"voyage_number" text,
	"carrier" text,
	"loading_port" text DEFAULT 'Port of Miami (USMIA)' NOT NULL,
	"discharge_port" text NOT NULL,
	"total_house_bills" integer DEFAULT 0 NOT NULL,
	"house_bill_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"total_receipts" integer DEFAULT 0 NOT NULL,
	"receipt_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"total_packages" integer DEFAULT 0 NOT NULL,
	"total_pieces" integer DEFAULT 0 NOT NULL,
	"total_weight_lbs" numeric(10, 2) DEFAULT '0.00',
	"total_weight_kg" numeric(10, 2) DEFAULT '0.00',
	"total_cft" numeric(10, 2) DEFAULT '0.00',
	"total_cbm" numeric(10, 2) DEFAULT '0.00',
	"container_fill_percentage" numeric(5, 2) DEFAULT '0.00',
	"assigned_shipment_id" text,
	"assigned_master_bl_id" text,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "consolidations_consolidation_number_unique" UNIQUE("consolidation_number")
);
--> statement-breakpoint
CREATE TABLE "bills_of_lading" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"bl_number" text NOT NULL,
	"type" text DEFAULT 'Master Ocean Bill of Lading' NOT NULL,
	"status" text DEFAULT 'Draft' NOT NULL,
	"shipment_id" text,
	"shipment_number" text,
	"consolidation_id" uuid,
	"house_bill_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_date" text NOT NULL,
	"issue_date" text,
	"shipper" jsonb NOT NULL,
	"consignee" jsonb NOT NULL,
	"notify_party" jsonb,
	"agent_id" uuid,
	"agent_name" text,
	"pre_carriage_by" text,
	"place_of_receipt" text,
	"ocean_vessel" text,
	"voyage_number" text,
	"carrier" text,
	"port_of_loading" text NOT NULL,
	"port_of_discharge" text NOT NULL,
	"place_of_delivery" text,
	"container_number" text,
	"seal_number" text,
	"container_type" text,
	"marks_and_numbers" text,
	"cargo_description" text,
	"package_count" integer DEFAULT 0 NOT NULL,
	"total_pieces" integer DEFAULT 0 NOT NULL,
	"package_type" text,
	"gross_weight_lbs" numeric(10, 2) DEFAULT '0.00',
	"gross_weight_kg" numeric(10, 2) DEFAULT '0.00',
	"cbm" numeric(10, 2) DEFAULT '0.00',
	"cft" numeric(10, 2) DEFAULT '0.00',
	"freight_payable_at" text DEFAULT 'Miami, FL',
	"freight_terms" text DEFAULT 'Freight Prepaid' NOT NULL,
	"number_of_originals" text DEFAULT '3 (THREE)' NOT NULL,
	"hold_details" jsonb DEFAULT '{"isOnHold":false}'::jsonb NOT NULL,
	"charges" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"total_freight_usd" numeric(10, 2) DEFAULT '0.00',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "bills_of_lading_bl_number_unique" UNIQUE("bl_number")
);
--> statement-breakpoint
CREATE TABLE "manifests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"manifest_number" text NOT NULL,
	"type" text DEFAULT 'Ocean Cargo Inward / Outward Manifest' NOT NULL,
	"title" text NOT NULL,
	"vessel_name" text NOT NULL,
	"voyage_number" text NOT NULL,
	"flag" text,
	"master_name" text,
	"port_of_loading" text NOT NULL,
	"port_of_discharge" text NOT NULL,
	"departure_date" text,
	"arrival_date" text,
	"carrier" text,
	"total_bls" integer DEFAULT 1 NOT NULL,
	"total_house_bills" integer DEFAULT 0 NOT NULL,
	"total_containers" integer DEFAULT 1 NOT NULL,
	"total_packages" integer DEFAULT 0 NOT NULL,
	"total_pieces" integer DEFAULT 0 NOT NULL,
	"total_weight_lbs" numeric(10, 2) DEFAULT '0.00',
	"total_weight_kg" numeric(10, 2) DEFAULT '0.00',
	"total_cbm" numeric(10, 2) DEFAULT '0.00',
	"total_cft" numeric(10, 2) DEFAULT '0.00',
	"status" text DEFAULT 'Generated' NOT NULL,
	"master_bl_number" text,
	"line_items" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "manifests_manifest_number_unique" UNIQUE("manifest_number")
);
--> statement-breakpoint
CREATE TABLE "shipments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"shipment_number" text NOT NULL,
	"type" text DEFAULT 'Ocean LCL Consolidation' NOT NULL,
	"service_mode" text DEFAULT 'Port-to-Port' NOT NULL,
	"status" text DEFAULT 'Cargo Received' NOT NULL,
	"tracking_number" text NOT NULL,
	"origin" text NOT NULL,
	"destination" text NOT NULL,
	"destination_port" text NOT NULL,
	"destination_code" text NOT NULL,
	"agent_id" uuid,
	"agent_name" text,
	"vessel_name" text,
	"voyage_number" text,
	"carrier" text,
	"container_number" text,
	"container_type" text,
	"seal_number" text,
	"bill_of_lading_id" text,
	"bill_of_lading_number" text,
	"bl_status" text,
	"manifest_number" text,
	"total_packages" integer DEFAULT 0 NOT NULL,
	"total_weight_lbs" numeric(10, 2) DEFAULT '0.00',
	"total_weight_kg" numeric(10, 2) DEFAULT '0.00',
	"total_cft" numeric(10, 2) DEFAULT '0.00',
	"total_cbm" numeric(10, 2) DEFAULT '0.00',
	"etd" text,
	"eta" text,
	"created_date" text NOT NULL,
	"warehouse_receipt_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"consolidation_id" text,
	"current_location" text,
	"tracking_checkpoints" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "shipments_shipment_number_unique" UNIQUE("shipment_number"),
	CONSTRAINT "shipments_tracking_number_unique" UNIQUE("tracking_number")
);
--> statement-breakpoint
CREATE TABLE "documents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"document_number" text,
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"document_type" text NOT NULL,
	"file_name" text NOT NULL,
	"file_url" text,
	"mime_type" text,
	"file_size" integer,
	"status" text DEFAULT 'Generated' NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "documents_document_number_unique" UNIQUE("document_number")
);
--> statement-breakpoint
CREATE TABLE "tracking_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tracking_number" text NOT NULL,
	"shipment_id" uuid,
	"stage" text NOT NULL,
	"status" text DEFAULT 'Completed' NOT NULL,
	"event_date" text NOT NULL,
	"event_time" text,
	"location" text NOT NULL,
	"notes" text,
	"checkpoint_index" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"log_number" text NOT NULL,
	"timestamp" text NOT NULL,
	"user_id" uuid,
	"user_name" text NOT NULL,
	"user_role" text,
	"module" text NOT NULL,
	"action" text NOT NULL,
	"record_id" text,
	"description" text NOT NULL,
	"ip_address" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "audit_logs_log_number_unique" UNIQUE("log_number")
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"key" text NOT NULL,
	"value" jsonb NOT NULL,
	"description" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "settings_key_unique" UNIQUE("key")
);
--> statement-breakpoint
ALTER TABLE "permissions" ADD CONSTRAINT "permissions_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warehouse_receipts" ADD CONSTRAINT "warehouse_receipts_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warehouse_receipts" ADD CONSTRAINT "warehouse_receipts_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cargo" ADD CONSTRAINT "cargo_warehouse_receipt_id_warehouse_receipts_id_fk" FOREIGN KEY ("warehouse_receipt_id") REFERENCES "public"."warehouse_receipts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "house_bills" ADD CONSTRAINT "house_bills_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "house_bills" ADD CONSTRAINT "house_bills_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voyages" ADD CONSTRAINT "voyages_vessel_id_vessels_id_fk" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consolidations" ADD CONSTRAINT "consolidations_container_id_containers_id_fk" FOREIGN KEY ("container_id") REFERENCES "public"."containers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consolidations" ADD CONSTRAINT "consolidations_vessel_id_vessels_id_fk" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consolidations" ADD CONSTRAINT "consolidations_voyage_id_voyages_id_fk" FOREIGN KEY ("voyage_id") REFERENCES "public"."voyages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bills_of_lading" ADD CONSTRAINT "bills_of_lading_consolidation_id_consolidations_id_fk" FOREIGN KEY ("consolidation_id") REFERENCES "public"."consolidations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bills_of_lading" ADD CONSTRAINT "bills_of_lading_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shipments" ADD CONSTRAINT "shipments_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracking_events" ADD CONSTRAINT "tracking_events_shipment_id_shipments_id_fk" FOREIGN KEY ("shipment_id") REFERENCES "public"."shipments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;