export const APP_CONSTANTS = {
  API_PREFIX: '/api/v1',
  DEFAULT_PORT: 5000,
  DEFAULT_HOST: '0.0.0.0',
  WAREHOUSE_RECEIPT_START_NUMBER: 3100,
  UNITS: {
    WEIGHT_LBS: 'LBS',
    WEIGHT_KG: 'KG',
    DIMENSION_INCHES: 'INCHES',
    VOLUME_CFT: 'CFT',
    VOLUME_CBM: 'CBM',
    CURRENCY_USD: 'USD',
  },
  CONVERSIONS: {
    INCHES_TO_CFT_DIVISOR: 1728,
    CFT_TO_CBM_MULTIPLIER: 0.0283168,
    LBS_TO_KG_MULTIPLIER: 0.453592,
  },
} as const;
